### ISSUE TITLE
[FEAT] Track

### ISSUE THREAD

**Issue by CodewithKisha** [codeclannigeria/codeclannigeria-frontend#8]
Track is the path that the user wants to specialize in.

**The following should be made available:**

1. Title - timelines/ Path such as frontend, backend, or mobile.
2. Description: Detailed description of what each path entails.

After choosing track, Mentees/Users should be able to select the stage(newbie, amateur, pro) that suits them

**Comment by Semiteagain** [comment]
Good Morning, Kisha you have unassigned me again.
what is the task about?

**Comment by CodewithKisha** [comment]
Good morning..uhmmm it's a frontend task, Rammy will assign us what to do.
Tayormi said I should help him and create Issues.

**Comment by Semiteagain** [comment]
Okay, I will be waiting for the task.
